INPUT_SIZE: 2280
WEIGHT: "weights/icdar2015_hourglass88.pth"
CHAR_DICT_FILE: "config/char_dict.txt"
WORD_LEXICON_PATH: "config/GenericVocabulary.txt"
SHORTWORD_LEXICON_PATH: "config/ShortVocabulary.txt"
RESULTS_SEPARATOR: ","
SIZE_DIVISIBILITY: 128
